version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-u', 'root']
      interval: 1s
      timeout: 3s
      retries: 3
    env_file:
      - .env
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"

  django:
    container_name: django
    volumes:
      - ./app:/var/lib/django/app
      - static_files:/var/lib/django/app/static
    build: ./app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    expose:
      - 8000

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    volumes:
      - static_files:/var/lib/nginx/static
    depends_on:
      - django
    ports:
      - "80:80"

volumes:
  static_files:
